# Generated by Django 4.2 on 2024-03-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToxicantEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToxicantPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Toxicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.IntegerField(choices=[(1, 'Least harmful'), (2, 'Moderately harmful'), (3, 'Harmful'), (4, 'Very harmful')])),
                ('toxicant_en', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='food.toxicanten')),
                ('toxicant_pl', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='food.toxicantpl')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('adding_date', models.DateField(auto_now_add=True)),
                ('toxicants', models.ManyToManyField(to='food.toxicant')),
            ],
        ),
    ]
