# Generated by Django 4.2 on 2024-03-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_toxicanten_medical_risks_toxicantpl_medical_risks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxicanten',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='toxicantpl',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
