# Generated by Django 4.2 on 2024-04-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_toxicanten_names_toxicantpl_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxicant',
            name='scale',
            field=models.IntegerField(choices=[(1, 'least harmful'), (2, 'moderately harmful'), (3, 'harmful'), (4, 'very harmful')]),
        ),
        migrations.AlterField(
            model_name='toxicanten',
            name='names',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
