# Generated by Django 4.2 on 2024-04-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_toxicanten_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxicant',
            name='toxicant_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.toxicanten'),
        ),
        migrations.AlterField(
            model_name='toxicant',
            name='toxicant_pl',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.toxicantpl'),
        ),
        migrations.AlterField(
            model_name='toxicanten',
            name='medical_risks',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toxicanten',
            name='names',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toxicantpl',
            name='medical_risks',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toxicantpl',
            name='names',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
