# Generated by Django 4.2 on 2024-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_toxicant_toxicant_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxicant',
            name='scale',
            field=models.IntegerField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high'), ('very high', 'very high')]),
        ),
    ]
