# Generated by Django 4.2 on 2024-04-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_toxicant_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxicant',
            name='scale',
            field=models.CharField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high'), ('very high', 'very high')], default='very high', max_length=10),
        ),
    ]
