# Generated by Django 4.2 on 2024-04-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_alter_toxicant_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toxicant',
            name='scale',
            field=models.CharField(choices=[('l', 'low'), ('m', 'moderate'), ('h', 'high'), ('vh', 'very high')], max_length=10),
        ),
    ]
