# Generated by Django 4.2.11 on 2024-04-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_image_modified_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='modified_image',
        ),
    ]
