# Generated by Django 4.2.11 on 2024-04-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_remove_image_modified_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
